### ISSUE TITLE
Bug: The size of tensor a (640) must match the size of tensor b (320)

### ISSUE THREAD

**Issue by bluadept** [magic-quill/MagicQuill#100]
**PLEASE READ BEFORE SUBMITTING AN ISSUE**  

MagicQuill is not a commercial software but a research project. While we strive to improve and maintain it, support is provided on a best-effort basis. Please be patient and respectful in your communications.
To help us respond faster and better, please ensure the following:  

1. **Search Existing Resources**: Have you looked through the documentation (e.g., hardware requirement and setup steps), and searched online for potential solutions?  
2. **Avoid Duplication**: Check if a similar issue already exists.  

If the issue persists, fill out the details below.

---

### **Checklist**

- [X] I have searched the documentation and FAQs.  
- [X] I have searched for similar issues but couldn’t find a solution.  
- [X] I have provided clear and detailed information about the issue.  

---

### **Issue/Feature Request Description**

**Type of Issue:**  
- [x] Bug  

**Summary**:  
Installed MagicQuill on my Windows Server.
     Windows Server 2022
     Intel Core I9 13900
     16 GB of memory
     NVIDIA T1000 8G GPU

---

### **Steps to Reproduce (For Bugs Only)**  
1.  Pull the image Girl_at_Beach.jpg into the copy image section of the webpage (this operates normally)
2.  using the + quill place a small area where the image will be placed.
3.  Click the run button which runs for a while then gives the error.

**Expected Behavior**:  
Add an item to the picture

**Actual Behavior**:  
Starts to process then give error message
The size of tensor a (640) must match the size of tensor b (320)
Does not matter what the size of the edit is

---

### **Additional Context/Details** 
This is the log running for the instance of MagicQuill 
Requested to load SD1ClipModel
Loading 1 new model
Apply edge controlnet
C:\Windows\System32\MagicQuill\MagicQuill\pidi.py:334: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ..\torch\csrc\tensor\python_tensor.cpp:85.)
  buffer = torch.cuda.FloatTensor(shape[0], shape[1], 5 * 5).fill_(0)
Base model type: SD1.5
BrushNet image.shape = torch.Size([1, 512, 512, 3]) mask.shape = torch.Size([1, 512, 512])
Requested to load AutoencoderKL
Loading 1 new model
loading in lowvram mode 64.0
BrushNet CL: image_latents shape = torch.Size([1, 4, 64, 64]) interpolated_mask shape = torch.Size([1, 1, 64, 64])
Requested to load BaseModel
Requested to load ControlNet
Loading 2 new models
loading in lowvram mode 64.0
loading in lowvram mode 64.0
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]BrushNet inference: do_classifier_free_guidance is True
BrushNet inference, step = 0: image batch = 1, got 2 latents, starting from 0
BrushNet inference: sample torch.Size([2, 4, 64, 64]) , CL torch.Size([2, 5, 64, 64]) dtype torch.float16
C:\ProgramData\anaconda3\envs\MagicQuill\lib\site-packages\diffusers\models\resnet.py:323: FutureWarning: `scale` is deprecated and will be removed in version 1.0.0. The `scale` argument is deprecated and will be ignored. Please remove it, as passing it will raise an error in the future. `scale` should directly be passed while calling the underlying pipeline component i.e., via `cross_attention_kwargs`.
  deprecate("scale", "1.0.0", deprecation_message)
BrushNet can't find <class 'comfy.ops.disable_weight_init.Conv2d'> layer in 0 input block: None
  0%|                                                                                           | 0/20 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\MagicQuill\lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "C:\ProgramData\anaconda3\envs\MagicQuill\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\ProgramData\anaconda3\envs\MagicQuill\lib\site-packages\gradio\blocks.py", line 2018, in process_api
    result = await self.call_function(
  File "C:\ProgramData\anaconda3\envs\MagicQuill\lib\site-packages\gradio\blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\ProgramData\anaconda3\envs\MagicQuill\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\ProgramData\anaconda3\envs\MagicQuill\lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\anaconda3\envs\MagicQuill\lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "C:\ProgramData\anaconda3\envs\MagicQuill\lib\site-packages\gradio\utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "C:\Windows\System32\MagicQuill\gradio_run.py", line 155, in generate_image_handler
    res = generate(
  File "C:\Windows\System32\MagicQuill\gradio_run.py", line 123, in generate
    latent_samples, final_image, lineart_output, color_output = scribbleColorEditModel.process(
  File "C:\Windows\System32\MagicQuill\MagicQuill\scribble_color_edit.py", line 110, in process
    latent_samples = self.ksampler.sample(
  File "C:\Windows\System32\MagicQuill\MagicQuill\comfyui_utils.py", line 154, in sample
    return self.common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "C:\Windows\System32\MagicQuill\MagicQuill\comfyui_utils.py", line 146, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "C:\Windows\System32\MagicQuill\MagicQuill\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Windows\System32\MagicQuill\MagicQuill\comfy\samplers.py", line 794, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Windows\System32\MagicQuill\MagicQuill\model_patch.py", line 120, in modified_sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "C:\Windows\System32\MagicQuill\MagicQuill\comfy\samplers.py", line 683, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "C:\Windows\System32\MagicQuill\MagicQuill\comfy\samplers.py", line 662, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "C:\Windows\System32\MagicQuill\MagicQuill\comfy\samplers.py", line 567, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "C:\ProgramData\anaconda3\envs\MagicQuill\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Windows\System32\MagicQuill\MagicQuill\comfy\k_diffusion\sampling.py", line 159, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Windows\System32\MagicQuill\MagicQuill\comfy\samplers.py", line 291, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "C:\Windows\System32\MagicQuill\MagicQuill\comfy\samplers.py", line 649, in __call__
    return self.predict_noise(*args, **kwargs)
  File "C:\Windows\System32\MagicQuill\MagicQuill\comfy\samplers.py", line 652, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "C:\Windows\System32\MagicQuill\MagicQuill\comfy\samplers.py", line 277, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "C:\Windows\System32\MagicQuill\MagicQuill\comfy\samplers.py", line 224, in calc_cond_batch
    output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
  File "C:\Windows\System32\MagicQuill\MagicQuill\model_patch.py", line 52, in brushnet_model_function_wrapper
    return apply_model_method(x, timestep, **options_dict['c'])
  File "C:\Windows\System32\MagicQuill\MagicQuill\comfy\model_base.py", line 113, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "C:\ProgramData\anaconda3\envs\MagicQuill\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\MagicQuill\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Windows\System32\MagicQuill\MagicQuill\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 852, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "C:\Windows\System32\MagicQuill\MagicQuill\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 44, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "C:\ProgramData\anaconda3\envs\MagicQuill\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\MagicQuill\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Windows\System32\MagicQuill\MagicQuill\brushnet_nodes.py", line 1070, in forward_patched_by_brushnet
    h += to_add.to(h.dtype).to(h.device)
RuntimeError: The size of tensor a (640) must match the size of tensor b (320) at non-singleton dimension 1

---

### **Environment**  
- **OS**:
- Windows Server 2022  
- **Version**:  
- **Any Relevant Dependencies**:  
![Girl_At_Beach](https://github.com/user-attachments/assets/10bc50fb-346f-425d-887e-1ebf9083c33b)

---

**Comment by zliucz** [comment]
Hi, check this [issues#43](https://github.com/magic-quill/MagicQuill/issues/43).
