### ISSUE TITLE
Google collab version? 

### ISSUE THREAD

**Issue by MahdeenSky** [magic-quill/MagicQuill#24]
Tried setting it up in google collab but I cannot load any images and ran into problems.

**Comment by mkasajim** [comment]
I also faced similar issue

**Comment by zliucz** [comment]
Can you present me some error logs?

**Comment by JimPresting** [comment]
> Can you present me some error logs?

There is endless errors - huge problems with all the versions and locations of all the libraries 

We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
Traceback (most recent call last):
  File "/content/drive/MyDrive/MagicQuill_Project/MagicQuill/gradio_run.py", line 25, in <module>
    scribbleColorEditModel = ScribbleColorEditModel()
  File "/content/drive/MyDrive/MagicQuill_Project/MagicQuill/MagicQuill/scribble_color_edit.py", line 29, in __init__
    self.model, self.clip, self.vae = self.checkpoint_loader.load_checkpoint(self.ckpt_name)
  File "/content/drive/MyDrive/MagicQuill_Project/MagicQuill/MagicQuill/comfyui_utils.py", line 85, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
  File "/content/drive/MyDrive/MagicQuill_Project/MagicQuill/MagicQuill/comfy/sd.py", line 498, in load_checkpoint_guess_config
    sd = comfy.utils.load_torch_file(ckpt_path)
  File "/content/drive/MyDrive/MagicQuill_Project/MagicQuill/MagicQuill/comfy/utils.py", line 13, in load_torch_file
    if ckpt.lower().endswith(".safetensors"):
AttributeError: 'NoneType' object has no attribute 'lower'

ERROR conda.cli.main_run:execute(125): `conda run python gradio_run.py` failed. (See above for error)

**Comment by JimPresting** [comment]
> Can you present me some error logs?

@zliucz do you have any guide on how to properly install it in Google Colab? Cause by all means I really cant get it to run. Locally - easy to problem but within Google Cloud setting the folders in my private Drive - no chance.
