### ISSUE TITLE
keyerro

### ISSUE THREAD

**Issue by dzbbdawang** [magic-quill/MagicQuill#29]
Traceback (most recent call last):
  File "C:\mofa_Draw\MagicQuill\gradio_run.py", line 20, in <module>
    scribbleColorEditModel = ScribbleColorEditModel()
  File "C:\mofa_Draw\MagicQuill\MagicQuill\scribble_color_edit.py", line 30, in __init__
    self.load_models('SD1.5', 'float16')
  File "C:\mofa_Draw\MagicQuill\MagicQuill\scribble_color_edit.py", line 43, in load_models
    self.brushnet = self.brushnet_loader.brushnet_loading(brushnet_name, dtype)[0]
  File "C:\mofa_Draw\MagicQuill\MagicQuill\brushnet_nodes.py", line 58, in brushnet_loading
    brushnet_file = os.path.join(self.inpaint_files[brushnet],brushnet)
KeyError: 'diffusion_pytorch_model.safetensors'    I am using Windows and following the recommended steps

**Comment by mertkemal1131** [comment]
I had this error today also, restarting my pc seems like fixed it for now
Interestingly it happened to me after i ran a gpu intensive program so might have been the cause for me

**Comment by aliok222** [comment]
same err

**Comment by zliucz** [comment]
Hi, we made a fix today. Try to pull the latest code and see if it works.
