### ISSUE TITLE
I am running into numpy not available problem when loading the first images

### ISSUE THREAD

**Issue by edtse** [magic-quill/MagicQuill#31]
Platform: windows

I am getting this error when I load an image :
`INFO:     127.0.0.1:56390 - "GET /static/fonts/ui-sans-serif/ui-sans-serif-Regular.woff2 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:56390 - "GET /static/fonts/system-ui/system-ui-Regular.woff2 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:56398 - "POST /magic_quill/process_background_img HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\edwar\miniconda3\envs\MagicQuill\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\edwar\AI\MagicQuill\gradio_run.py", line 331, in process_background_img
    resized_img_tensor = load_and_resize_image(img)
  File "C:\Users\edwar\AI\MagicQuill\gradio_run.py", line 73, in load_and_resize_image
    image_tensor = torch.from_numpy(image_array)[None,]
RuntimeError: Numpy is not available`

I am quite sure numpy is install:

pip install numpy
Requirement already satisfied: numpy in c:\users\edwar\miniconda3\envs\magicquill\lib\site-packages (1.26.4)

Does anyone know how I could solve this problem?

**Comment by zliucz** [comment]
Hi, weird bug. This error may happen when numpy isn't properly accessible to PyTorch. Maybe try to re-install pytorch using
 ```
pip install torch==2.1.2 torchvision==0.16.2 --index-url https://download.pytorch.org/whl/cu118
```
Thanks.

**Comment by edtse** [comment]
pip uninstall torch torchvision numpy

then install with 

pip install torch==2.1.2 torchvision==0.16.2 --index-url https://download.pytorch.org/whl/cu118

This solved the problem, thanks.
