### ISSUE TITLE
Traceback (most recent call last):   File "/root/MagicQuill/gradio_run.py", line 19, in <module>

### ISSUE THREAD

**Issue by unsiao** [magic-quill/MagicQuill#32]
我在Linux上部署的时候出现问题:
```
(MagicQuill) root@dsw-434669-8df9756db-w7th9:~/MagicQuill# CUDA_VISIBLE_DEVICES=0 python gradio_run.py
Total VRAM 22732 MB, total RAM 6144 MB
pytorch version: 2.1.2+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA A10 : native
Using pytorch cross attention
/root/anaconda3/envs/MagicQuill/lib/python3.10/site-packages/_distutils_hack/__init__.py:54: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
['/root/MagicQuill', '/root/anaconda3/envs/MagicQuill/lib/python310.zip', '/root/anaconda3/envs/MagicQuill/lib/python3.10', '/root/anaconda3/envs/MagicQuill/lib/python3.10/lib-dynload', '/root/anaconda3/envs/MagicQuill/lib/python3.10/site-packages', '__editable__.llava-1.2.2.post1.finder.__path_hook__', '/root/MagicQuill/MagicQuill', '/root/anaconda3/envs/MagicQuill/lib/python3.10/site-packages/setuptools/_vendor']
Traceback (most recent call last):
  File "/root/anaconda3/envs/MagicQuill/lib/python3.10/site-packages/transformers/utils/hub.py", line 385, in cached_file
    resolved_file = hf_hub_download(
  File "/root/anaconda3/envs/MagicQuill/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/root/anaconda3/envs/MagicQuill/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/root/MagicQuill/MagicQuill/../models/llava-v1.5-7b-finetune-clean'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/MagicQuill/gradio_run.py", line 19, in <module>
    llavaModel = LLaVAModel()
  File "/root/MagicQuill/MagicQuill/llava_new.py", line 26, in __init__
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
  File "/root/MagicQuill/MagicQuill/LLaVA/llava/model/builder.py", line 116, in load_pretrained_model
    tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
  File "/root/anaconda3/envs/MagicQuill/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 758, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/MagicQuill/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 590, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/root/anaconda3/envs/MagicQuill/lib/python3.10/site-packages/transformers/utils/hub.py", line 450, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: '/root/MagicQuill/MagicQuill/../models/llava-v1.5-7b-finetune-clean'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
```

**Comment by zliucz** [comment]
Hi, change the 25th line of [llava_new.py](https://github.com/magic-quill/MagicQuill/blob/main/MagicQuill/llava_new.py) to the correct path of the llava model. Let me know if it works. Thanks

**Comment by vixenius** [comment]
for llava to work you will also need to add this line of code in gradio_run.py

Line 19 is llava model path, for my pc its    llava_model_path = "D:\AINOVO\MagicQuill\MagicQuill-models\llava-v1.5-7b-finetune-clean"

Line 20:       llavaModel = LLaVAModel()
