### ISSUE TITLE
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars

### ISSUE THREAD

**Issue by Alan-Chiuth** [magic-quill/MagicQuill#54]
Followed instruction trying to install MagicQuill. Run the "windows_setup.bat".
Below is the error when starting MagicQuill

Starting MagicQuill...
Total VRAM 16376 MB, total RAM 32598 MB
pytorch version: 2.1.2+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : native
Using pytorch cross attention
['C:\\GenAI\\MagicQuill', 'C:\\ProgramData\\miniconda3\\envs\\MagicQuill\\python310.zip', 'C:\\ProgramData\\miniconda3\\envs\\MagicQuill\\DLLs', 'C:\\ProgramData\\miniconda3\\envs\\MagicQuill\\lib', 'C:\\ProgramData\\miniconda3\\envs\\MagicQuill', 'C:\\ProgramData\\miniconda3\\envs\\MagicQuill\\lib\\site-packages', '__editable__.llava-1.2.2.post1.finder.__path_hook__', 'C:\\GenAI\\MagicQuill\\MagicQuill']
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\MagicQuill\lib\site-packages\transformers\utils\hub.py", line 385, in cached_file    resolved_file = hf_hub_download(
  File "C:\ProgramData\miniconda3\envs\MagicQuill\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\ProgramData\miniconda3\envs\MagicQuill\lib\site-packages\huggingface_hub\utils\_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'C:\GenAI\MagicQuill\models\llava-v1.5-7b-finetune-clean'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\GenAI\MagicQuill\gradio_run.py", line 21, in <module>
    llavaModel = LLaVAModel()
  File "C:\GenAI\MagicQuill\MagicQuill\llava_new.py", line 26, in __init__
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
  File "C:\GenAI\MagicQuill\MagicQuill\LLaVA\llava\model\builder.py", line 116, in load_pretrained_model
    tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
  File "C:\ProgramData\miniconda3\envs\MagicQuill\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 758, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "C:\ProgramData\miniconda3\envs\MagicQuill\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 590, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "C:\ProgramData\miniconda3\envs\MagicQuill\lib\site-packages\transformers\utils\hub.py", line 450, in cached_file    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'C:\GenAI\MagicQuill\models\llava-v1.5-7b-finetune-clean'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
Error: Failed to run MagicQuill.
Press any key to continue . . .

**Comment by zliucz** [comment]
Hi, would you please take a screenshot of your folder at path `C:\GenAI\MagicQuill\models\llava-v1.5-7b-finetune-clean`?

**Comment by Alan-Chiuth** [comment]
Thanks for the hint. Found the issue. My folder path is **C:\GenAI\MagicQuill\models\models\llava-v1.5-7b-finetune-clean instead**. Problem solved after moving to **C:\GenAI\MagicQuill\models\models\llava-v1.5-7b-finetune-clean instead**
