### ISSUE TITLE
Error starting: huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars

### ISSUE THREAD

**Issue by TheOnlySheet** [magic-quill/MagicQuill#62]
### **Checklist**

- [ yes] I have searched the documentation and FAQs.  Yes, no luck
- [ yes] I have searched for similar issues but couldn’t find a solution.  No luck.
- [ hopefully] I have provided clear and detailed information about the issue.  

---

### **Issue Description**

**Type of Issue:**  
- Error when using **python gradio_run.py**
- Steps followed for installation: https://youtu.be/cZQpB0Ptubo
- Previous steps followed (which failed): https://youtu.be/wTIfxdFoXm8

**Summary**:  
  
Help! I tried again to install this on my Win 11 PC; when starting, I get this error:

(MagicQuill2) D:\magicquill\MagicQuill>python gradio_run.py

```
Total VRAM 8192 MB, total RAM 32702 MB
pytorch version: 2.1.2+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 SUPER : native
Using pytorch cross attention
['D:\\magicquill\\MagicQuill', 'D:\\Users\\username\\miniconda3\\envs\\MagicQuill2\\python310.zip', 'D:\\Users\\username\\miniconda3\\envs\\MagicQuill2\\DLLs', 'D:\\Users\\username\\miniconda3\\envs\\MagicQuill2\\lib', 'D:\\Users\\username\\miniconda3\\envs\\MagicQuill2', 'D:\\Users\\username\\miniconda3\\envs\\MagicQuill2\\lib\\site-packages', '__editable__.llava-1.2.2.post1.finder.__path_hook__', 'D:\\magicquill\\MagicQuill\\MagicQuill']
Traceback (most recent call last):
  File "D:\Users\username\miniconda3\envs\MagicQuill2\lib\site-packages\transformers\utils\hub.py", line 385, in cached_file
    resolved_file = hf_hub_download(
  File "D:\Users\username\miniconda3\envs\MagicQuill2\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\Users\username\miniconda3\envs\MagicQuill2\lib\site-packages\huggingface_hub\utils\_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'D:\magicquill\MagicQuill\models\llava-v1.5-7b-finetune-clean'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\magicquill\MagicQuill\gradio_run.py", line 21, in <module>
    llavaModel = LLaVAModel()
  File "D:\magicquill\MagicQuill\MagicQuill\llava_new.py", line 26, in __init__
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
  File "D:\magicquill\MagicQuill\MagicQuill\LLaVA\llava\model\builder.py", line 116, in load_pretrained_model
    tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
  File "D:\Users\username\miniconda3\envs\MagicQuill2\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 758, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "D:\Users\username\miniconda3\envs\MagicQuill2\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 590, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "D:\Users\username\miniconda3\envs\MagicQuill2\lib\site-packages\transformers\utils\hub.py", line 450, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'D:\magicquill\MagicQuill\models\llava-v1.5-7b-finetune-clean'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
```
---

### **Steps to Reproduce (For Bugs Only)**  
Unknown
---

### **Environment**  
- **OS**:  Win
- **Version**:  11
- **Any Relevant Dependencies**:

**Comment by zliucz** [comment]
Hi, check this [issue#54](https://github.com/magic-quill/MagicQuill/issues/54).

**Comment by TheOnlySheet** [comment]
> Hi, check this [issue#54](https://github.com/magic-quill/MagicQuill/issues/54). Take a screenshot at your folder at path `D:\magicquill\MagicQuill\models\llava-v1.5-7b-finetune-clean` would help us find the problem.

Arggg.. I see the error... Model folder INSIDE the Model folder - I couldn't find a way to see older bug reports.
THANKS for fixing!!!
