### ISSUE TITLE
Regarding the issue of CUDA tensors

### ISSUE THREAD

**Issue by MikeAiJF** [magic-quill/MagicQuill#64]
**PLEASE READ BEFORE SUBMITTING AN ISSUE**  

MagicQuill is not a commercial software but a research project. While we strive to improve and maintain it, support is provided on a best-effort basis. Please be patient and respectful in your communications.
To help us respond faster and better, please ensure the following:  

1. **Search Existing Resources**: Have you looked through the documentation (e.g., hardware requirement and setup steps), and searched online for potential solutions?  
2. **Avoid Duplication**: Check if a similar issue already exists.  

If the issue persists, fill out the details below.

---

### **Checklist**

- [ ] I have searched the documentation and FAQs.  
- [ ] I have searched for similar issues but couldn’t find a solution.  
- [ ] I have provided clear and detailed information about the issue.  

---

### **Issue/Feature Request Description**

**Type of Issue:**  
- [ ] Bug  
- [ ] Feature Request  
- [ ] Question  

**Summary**:  
  

---

### **Steps to Reproduce (For Bugs Only)**  
1.  
2.  
3.  

**Expected Behavior**:  

**Actual Behavior**:  
  

---

### **Additional Context/Details**  

---

### **Environment**  
- **OS**:  
- **Version**:  
- **Any Relevant Dependencies**:  

---

### **Feature Request Specifics (If Applicable)**  
- **What problem does this solve?**:  
- **How will this feature improve the project?**:
Traceback (most recent call last):
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/project_03/MagicQuill/gradio_run.py", line 320, in guess_prompt
    res = guess_prompt_handler(data['original_image'], data['add_color_image'], data['add_edge_image'])
  File "/project_03/MagicQuill/gradio_run.py", line 109, in guess_prompt_handler
    res = guess(original_image_tensor, add_color_image_tensor, add_edge_mask)
  File "/project_03/MagicQuill/gradio_run.py", line 90, in guess
    description, ans1, ans2 = llavaModel.process(original_image_tensor, add_color_image_tensor, add_edge_mask)
  File "/project_03/MagicQuill/MagicQuill/llava_new.py", line 95, in process
    mean_brightness = image_with_sketch[bool_add_mask].mean()
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
INFO:     127.0.0.1:54310 - "POST /gradio_api/queue/join HTTP/1.1" 200 OK
Requested to load SD1ClipModel
Loading 1 new model
INFO:     127.0.0.1:54310 - "GET /gradio_api/queue/data?session_hash=i8htzq0dpzk HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/gradio/blocks.py", line 2018, in process_api
    result = await self.call_function(
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/gradio/blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/home/kmks-server-02/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/gradio/utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "/project_03/MagicQuill/gradio_run.py", line 152, in generate_image_handler
    res = generate(
  File "/project_03/MagicQuill/gradio_run.py", line 120, in generate
    latent_samples, final_image, lineart_output, color_output = scribbleColorEditModel.process(
  File "/project_03/MagicQuill/MagicQuill/scribble_color_edit.py", line 56, in process
    mask = self.mask_processor.expand_mask(mask, expand=grow_size, tapered_corners=True)[0]
  File "/project_03/MagicQuill/MagicQuill/comfyui_utils.py", line 388, in expand_mask
    output = m.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by MikeAiJF** [comment]
What's the reason? I didn't change the code

**Comment by zliucz** [comment]
I haven't met this error before. Would you please show me the environment list by pip list? Let's see if there's any mismatch.

**Comment by MikeAiJF** [comment]
![image](https://github.com/user-attachments/assets/b12f3761-5336-40eb-a908-3e722530a169)

**Comment by MikeAiJF** [comment]
是我显卡的原因吗

**Comment by zliucz** [comment]
@MikeAiJF Oh. Indeed. Try to use one and only GPU by running this command `CUDA_VISIBLE_DEVICES=0 python gradio_run.py`

**Comment by MikeAiJF** [comment]
> @MikeAiJF哦。确实如此。尝试通过运行此命令使用一个且仅一个 GPU `CUDA_VISIBLE_DEVICES=0 python gradio_run.py`。如果有效请告诉我。

Okay, thank you very much

**Comment by MikeAiJF** [comment]
Hello, may I only use the SD1.5 model? Can I use the Flux model for generation

**Comment by zliucz** [comment]
Hi, currently, we have only supported SD v1.5. But we have released our canvas UI, you may modify the code to support Flux by your own.

**Comment by aiikendoit** [comment]
i have an error, CUDA not found, I'm using radeon 7600xt
