### ISSUE TITLE
Error after post installation and first time running Magic quill

### ISSUE THREAD

**Issue by saa04** [magic-quill/MagicQuill#70]
(MagicQuill) D:\SD_AMD\MQuill\MagicQuill>set CUDA_VISIBLE_DEVICES=0 && python gradio_run.py
Traceback (most recent call last):
  File "D:\SD_AMD\MQuill\MagicQuill\gradio_run.py", line 17, in <module>
    from MagicQuill.scribble_color_edit import ScribbleColorEditModel
  File "D:\SD_AMD\MQuill\MagicQuill\MagicQuill\scribble_color_edit.py", line 9, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, get_files_with_extension
  File "D:\SD_AMD\MQuill\MagicQuill\MagicQuill\brushnet_nodes.py", line 11, in <module>
    import comfy.sd
  File "D:\SD_AMD\MQuill\MagicQuill\MagicQuill\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "D:\SD_AMD\MQuill\MagicQuill\MagicQuill\comfy\model_management.py", line 119, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "D:\SD_AMD\MQuill\MagicQuill\MagicQuill\comfy\model_management.py", line 88, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\ursti\miniconda3\envs\MagicQuill\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\ursti\miniconda3\envs\MagicQuill\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

---

### **Checklist**

- [x] I have searched the documentation and FAQs.  
- [x] I have searched for similar issues but couldn’t find a solution.  
- [x] I have provided clear and detailed information about the issue.  

---

### **Issue/Feature Request Description**

**Type of Issue:**  
- [ ] Bug  
- [ ] Feature Request  
- [x] Question

**Comment by bruceyyu** [comment]
https://discuss.pytorch.org/t/torch-not-compiled-with-cuda-enabled/112467/13

**Comment by rzgarespo** [comment]
1) install https://developer.nvidia.com/cuda-toolkit
2) reinstall -> pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118

**Comment by saa04** [comment]
> set CUDA_VISIBLE_DEVICES=0 && python gradio_run.py

Thank you it worked

**Comment by saa04** [comment]
> 1. install https://developer.nvidia.com/cuda-toolkit
> 2. reinstall -> pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118

Thank you it worked

**Comment by saa04** [comment]
donbe
