### ISSUE TITLE
import gradio as gr how to fix it?

### ISSUE THREAD

**Issue by Pasha0606** [magic-quill/MagicQuill#78]
**PLEASE READ BEFORE SUBMITTING AN ISSUE**  

MagicQuill is not a commercial software but a research project. While we strive to improve and maintain it, support is provided on a best-effort basis. Please be patient and respectful in your communications.
To help us respond faster and better, please ensure the following:  

1. **Search Existing Resources**: Have you looked through the documentation (e.g., hardware requirement and setup steps), and searched online for potential solutions?  
2. **Avoid Duplication**: Check if a similar issue already exists.  

If the issue persists, fill out the details below.

---

### **Checklist**

- [ ] I have searched the documentation and FAQs.  
- [ ] I have searched for similar issues but couldn’t find a solution.  
- [ ] I have provided clear and detailed information about the issue.  

---

### **Issue/Feature Request Description**

**Type of Issue:**  
- [ ] Bug  
- [ ] Feature Request  
- [ ] Question  

**Summary**:  
  

---

### **Steps to Reproduce (For Bugs Only)**  
1.  
2.  
3.  

**Expected Behavior**:  

**Actual Behavior**:  
  

---

### **Additional Context/Details**  

---

### **Environment**  
- **OS**:  
- **Version**:  
- **Any Relevant Dependencies**:  

---

### **Feature Request Specifics (If Applicable)**  
- **What problem does this solve?**:  
- **How will this feature improve the project?**:

**Comment by Pasha0606** [comment]
import gradio as gr
ModuleNotFoundError: No module named 'gradio'  how to fix it?

**Comment by rtx3060laptop** [comment]
conda deactivate

conda remove -n MagicQuill --all -y

conda create -n MagicQuill python=3.10 -y

conda activate MagicQuill

and continue the steps from the original installation page.

**Comment by Pasha0606** [comment]
İ GOT THİS ERROR NOW :( how to fix that

Traceback (most recent call last):
  File "C:\Users\Pasha\.conda\envs\MagicQuill\lib\site-packages\diffusers\utils\import_utils.py", line 853, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\Pasha\.conda\envs\MagicQuill\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Pasha\.conda\envs\MagicQuill\lib\site-packages\diffusers\loaders\unet.py", line 46, in <module>
    from .lora_pipeline import LORA_WEIGHT_NAME, LORA_WEIGHT_NAME_SAFE, TEXT_ENCODER_NAME, UNET_NAME
  File "C:\Users\Pasha\.conda\envs\MagicQuill\lib\site-packages\diffusers\loaders\lora_pipeline.py", line 36, in <module>
    from .lora_base import LoraBaseMixin
  File "C:\Users\Pasha\.conda\envs\MagicQuill\lib\site-packages\diffusers\loaders\lora_base.py", line 47, in <module>
    from peft.tuners.tuners_utils import BaseTunerLayer
  File "C:\Users\Pasha\.conda\envs\MagicQuill\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .auto import (
  File "C:\Users\Pasha\.conda\envs\MagicQuill\lib\site-packages\peft\auto.py", line 32, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "C:\Users\Pasha\.conda\envs\MagicQuill\lib\site-packages\peft\mapping.py", line 25, in <module>
    from .mixed_model import PeftMixedModel
  File "C:\Users\Pasha\.conda\envs\MagicQuill\lib\site-packages\peft\mixed_model.py", line 29, in <module>
    from .peft_model import PeftModel
  File "C:\Users\Pasha\.conda\envs\MagicQuill\lib\site-packages\peft\peft_model.py", line 37, in <module>
    from transformers import Cache, DynamicCache, EncoderDecoderCache, PreTrainedModel
ImportError: cannot import name 'EncoderDecoderCache' from 'transformers' (C:\Users\Pasha\.conda\envs\MagicQuill\lib\site-packages\transformers\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Magic\MagicQuill\gradio_run.py", line 17, in <module>
    from MagicQuill.scribble_color_edit import ScribbleColorEditModel
  File "E:\Magic\MagicQuill\MagicQuill\scribble_color_edit.py", line 9, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, get_files_with_extension
  File "E:\Magic\MagicQuill\MagicQuill\brushnet_nodes.py", line 21, in <module>
    from .brushnet.brushnet import BrushNetModel
  File "E:\Magic\MagicQuill\MagicQuill\brushnet\brushnet.py", line 20, in <module>
    from .unet_2d_blocks import (
  File "E:\Magic\MagicQuill\MagicQuill\brushnet\unet_2d_blocks.py", line 36, in <module>
    from diffusers.models.transformers.dual_transformer_2d import DualTransformer2DModel
  File "C:\Users\Pasha\.conda\envs\MagicQuill\lib\site-packages\diffusers\models\transformers\__init__.py", line 13, in <module>
    from .prior_transformer import PriorTransformer
  File "C:\Users\Pasha\.conda\envs\MagicQuill\lib\site-packages\diffusers\models\transformers\prior_transformer.py", line 9, in <module>
    from ...loaders import PeftAdapterMixin, UNet2DConditionLoadersMixin
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\Pasha\.conda\envs\MagicQuill\lib\site-packages\diffusers\utils\import_utils.py", line 843, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\Pasha\.conda\envs\MagicQuill\lib\site-packages\diffusers\utils\import_utils.py", line 855, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (C:\Users\Pasha\.conda\envs\MagicQuill\lib\site-packages\transformers\__init__.py)
