### ISSUE TITLE
how to fix someone help pls :(

### ISSUE THREAD

**Issue by Pasha0606** [magic-quill/MagicQuill#85]
**PLEASE READ BEFORE SUBMITTING AN ISSUE**  

MagicQuill is not a commercial software but a research project. While we strive to improve and maintain it, support is provided on a best-effort basis. Please be patient and respectful in your communications.
To help us respond faster and better, please ensure the following:  

1. **Search Existing Resources**: Have you looked through the documentation (e.g., hardware requirement and setup steps), and searched online for potential solutions?  
2. **Avoid Duplication**: Check if a similar issue already exists.  

If the issue persists, fill out the details below.

---

### **Checklist**

- [ ] I have searched the documentation and FAQs.  
- [ ] I have searched for similar issues but couldn’t find a solution.  
- [ ] I have provided clear and detailed information about the issue.  

---

### **Issue/Feature Request Description**

**Type of Issue:**  
- [ ] Bug  
- [ ] Feature Request  
- [ ] Question  

**Summary**:  
  

---

### **Steps to Reproduce (For Bugs Only)**  
1.  
2.  
3.  

**Expected Behavior**:  

**Actual Behavior**:  
  

---

### **Additional Context/Details**  

---

### **Environment**  
- **OS**:  
- **Version**:  
- **Any Relevant Dependencies**:  

---

### **Feature Request Specifics (If Applicable)**  
- **What problem does this solve?**:  
- **How will this feature improve the project?**:

**Comment by Pasha0606** [comment]
Loading checkpoint shards:  33%|███████████████████                                      | 1/3 [00:31<01:03, 31.94s/it]
Traceback (most recent call last):
  File "E:\MagicQuill\MagicQuill\gradio_run.py", line 24, in <module>
    llavaModel = LLaVAModel()
  File "E:\MagicQuill\MagicQuill\MagicQuill\llava_new.py", line 26, in __init__
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
  File "E:\MagicQuill\MagicQuill\MagicQuill\LLaVA\llava\model\builder.py", line 117, in load_pretrained_model
    model = LlavaLlamaForCausalLM.from_pretrained(
  File "E:\Users\Pasha\anaconda3\envs\magic\lib\site-packages\transformers\modeling_utils.py", line 3850, in from_pretrained
    ) = cls._load_pretrained_model(
  File "E:\Users\Pasha\anaconda3\envs\magic\lib\site-packages\transformers\modeling_utils.py", line 4259, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "E:\Users\Pasha\anaconda3\envs\magic\lib\site-packages\transformers\modeling_utils.py", line 506, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
(magic) (magic) PS E:\MagicQuill\MagicQuill>

**Comment by jbedgood** [comment]
I'm having the same issue with new install on manarjo. Can anyone help get this resolved?

`Traceback (most recent call last):
  File "/home/jbedgood/MagicQuill/gradio_run.py", line 24, in <module>
    llavaModel = LLaVAModel()
  File "/home/jbedgood/MagicQuill/MagicQuill/llava_new.py", line 26, in __init__
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
  File "/home/jbedgood/MagicQuill/MagicQuill/LLaVA/llava/model/builder.py", line 116, in load_pretrained_model
    tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
  File "/home/jbedgood/anaconda3/envs/MagicQuill/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 773, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/home/jbedgood/anaconda3/envs/MagicQuill/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1100, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/jbedgood/anaconda3/envs/MagicQuill/lib/python3.10/site-packages/transformers/configuration_utils.py", line 634, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/jbedgood/anaconda3/envs/MagicQuill/lib/python3.10/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/jbedgood/anaconda3/envs/MagicQuill/lib/python3.10/site-packages/transformers/utils/hub.py", line 356, in cached_file
    raise EnvironmentError(
OSError: /home/jbedgood/MagicQuill/models/llava-v1.5-7b-finetune-clean does not appear to have a file named config.json. Checkout 'https://huggingface.co//home/jbedgood/MagicQuill/models/llava-v1.5-7b-finetune-clean/None' for available files.`

**Comment by FurkanGozukara** [comment]
i have massed compute[ installers](https://www.patreon.com/posts/magicquill-1-for-117326651) shared which is based on ubuntu if you interested in

**Comment by jbedgood** [comment]
Is there not going to be any update on this issue?
