### ISSUE TITLE
Torch Issue: AttributeError: module 'torch' has no attribute 'uint1'

### ISSUE THREAD

**Issue by Pivo987** [magic-quill/MagicQuill#97]
![Screenshot 2024-12-23 092004](https://github.com/user-attachments/assets/229f28d4-8b12-4ab4-ab90-1ed8f160dc56)
**_Hello, I have installed everything step by step and properly on Windows.
I am actually having this issue, could someone help me please?_**

(MagicQuill) C:\Users\aaaaaaa\OneDrive\Desktop\MagicQuill>python gradio_run.py
Total VRAM 8192 MB, total RAM 32689 MB
pytorch version: 2.1.2+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : native

Using pytorch cross attention
Traceback (most recent call last):
  File "C:\Users\aaaaaaa\OneDrive\Desktop\MagicQuill\gradio_run.py", line 17, in <module>
    from MagicQuill.scribble_color_edit import ScribbleColorEditModel
  File "C:\Users\aaaaaaa\OneDrive\Desktop\MagicQuill\MagicQuill\scribble_color_edit.py", line 9, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, get_files_with_extension
  File "C:\Users\aaaaaaa\OneDrive\Desktop\MagicQuill\MagicQuill\brushnet_nodes.py", line 21, in <module>
    from .brushnet.brushnet import BrushNetModel
  File "C:\Users\aaaaaaa\OneDrive\Desktop\MagicQuill\MagicQuill\brushnet\brushnet.py", line 18, in <module>
    from diffusers.models.modeling_utils import ModelMixin
  File "C:\Users\aaaaaaa\miniconda3\envs\MagicQuill\lib\site-packages\diffusers\models\modeling_utils.py", line 35, in <module>
    from ..quantizers import DiffusersAutoQuantizer, DiffusersQuantizer
  File "C:\Users\aaaaaaa\miniconda3\envs\MagicQuill\lib\site-packages\diffusers\quantizers\__init__.py", line 15, in <module>
    from .auto import DiffusersAutoQuantizer
  File "C:\Users\aaaaaaa\miniconda3\envs\MagicQuill\lib\site-packages\diffusers\quantizers\auto.py", line 31, in <module>
    from .torchao import TorchAoHfQuantizer
  File "C:\Users\aaaaaaa\miniconda3\envs\MagicQuill\lib\site-packages\diffusers\quantizers\torchao\__init__.py", line 15, in <module>
    from .torchao_quantizer import TorchAoHfQuantizer
  File "C:\Users\aaaaaaa\miniconda3\envs\MagicQuill\lib\site-packages\diffusers\quantizers\torchao\torchao_quantizer.py", line 45, in <module>
    torch.uint1,
  File "C:\Users\aaaaaaa\miniconda3\envs\MagicQuill\lib\site-packages\torch\__init__.py", line 1833, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute 'uint1'

**Comment by armansh2210** [comment]
Same issue here as well

**Comment by elssantosr** [comment]
Same issue here as well

**Comment by GiannisCon** [comment]
i managed to resolve the issue by executing these commands:
first this:
pip uninstall torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2
then this:
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by elssantosr** [comment]
> @Pivo987 @armansh2210 i managed to resolve the issue by executing these commands: first this: pip uninstall torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 then this: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

this evolves for the following error:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
llava 1.2.2.post1 requires torch==2.1.2, but you have torch 2.5.1+cu118 which is incompatible.
llava 1.2.2.post1 requires torchvision==0.16.2, but you have torchvision 0.20.1+cu118 which is incompatible.

but even so, it goes thru the uint1 error.

thanks @GiannisCon

**Comment by GiannisCon** [comment]
i get the same error as you but it runs, i can use the app when i execute the command:
python gradio_run.py

**Comment by vhrs6** [comment]
same issue

**Comment by Pivo987** [comment]
> > @Pivo987 @armansh2210 i managed to resolve the issue by executing these commands: first this: pip uninstall torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 then this: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> 
> this evolves for the following error: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. llava 1.2.2.post1 requires torch==2.1.2, but you have torch 2.5.1+cu118 which is incompatible. llava 1.2.2.post1 requires torchvision==0.16.2, but you have torchvision 0.20.1+cu118 which is incompatible.
> 
> but even so, it goes thru the uint1 error.
> 
> thanks @GiannisCon

Same here. Error evolved, but now it is working at least. Thanks a lot @GiannisCon

**Comment by gjnave** [comment]
i belive the issue is that diffusers just updated yesteday.. been unable to get anything working but am attempting to try different versions of dependent packages

**Comment by thepilip** [comment]
> i get the same error as you but it runs, i can use the app when i execute the command:
python gradio_run.py

when i run gradio_run.py i get
OSError: Incorrect path_or_model_id: 'C:\Users\xxxxx\MagicQuill\models\llava-v1.5-7b-finetune-clean'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

**Comment by zliucz** [comment]
@thepilip Hi, check this [issue#54](https://github.com/magic-quill/MagicQuill/issues/54). Please download the llava checkpoint and place it in the correct path.
